#!/bin/bash

# Функция удаления отладочной информации
function strip_debug_info()
{
    if [ ! -L $1 ]; then
        res=$(file $1 | grep -E 'LSB +shared object|ar archive|LSB +relocatable')
        if [ -n "$res" ]; then
            echo "Stripped: $1"
            $SUDO strip --strip-debug --strip-unneeded $1
            return
        fi

        res=$(file $1 | grep -E 'LSB +executable')
        if [ -n "$res" ]; then
            echo "Stripped: $1"
            $SUDO strip --strip-all $1
            return
        fi

        res=$(file $1 | grep -E 'LSB +pie +executable')
        if [ -n "$res" ]; then
            echo "Stripped: $1"
            $SUDO strip --strip-all $1
            return
        fi
    fi
}
